### ISSUE TITLE
Set concordance for us-house constituencies 

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data-constituency-us#9]
EG for https://spelunker.whosonfirst.org/id/1108737357/ we'd set `wof:concordances` to include `uscensus:geoid` = `0200`. 

Let's try this on for size before doing it for more placetypes in this repo.

**Comment by stepps00** [comment]
https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/uscensus.json#L28

Noting that `uscensus` is not currently used in an existing concordance, so the `uscensus:geoid` works.
